# scripts/reporter.py
"""Report Generator — produces Markdown and PDF incident reports from triage analysis."""

import logging
from datetime import datetime
from pathlib import Path
from typing import Dict

logger = logging.getLogger(__name__)


class ReportGenerator:
    SEVERITY_LABELS = {
        (9, 10): ("CRITICAL", "🔴"),
        (7, 8):  ("HIGH",     "🟠"),
        (4, 6):  ("MEDIUM",   "🟡"),
        (1, 3):  ("LOW",      "🟢"),
    }

    def __init__(self, output_dir: str = "reports/", generate_pdf: bool = False):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.generate_pdf = generate_pdf

    def generate(self, alert: Dict, analysis: Dict) -> Dict[str, str]:
        report_id = self._generate_report_id(alert)
        severity_label, severity_icon = self._get_severity_label(
            analysis.get("severity_score", 0)
        )
        context = {
            "report_id": report_id,
            "generated_at": datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC"),
            "alert": alert,
            "analysis": analysis,
            "severity_label": severity_label,
            "severity_icon": severity_icon,
        }

        output_paths = {}
        md_path = self.output_dir / f"{report_id}.md"
        md_path.write_text(self._render_markdown(context), encoding="utf-8")
        output_paths["markdown"] = str(md_path)
        logger.info(f"Markdown report saved: {md_path}")

        if self.generate_pdf:
            try:
                pdf_path = self.output_dir / f"{report_id}.pdf"
                self._render_pdf(context, pdf_path)
                output_paths["pdf"] = str(pdf_path)
                logger.info(f"PDF report saved: {pdf_path}")
            except Exception as e:
                logger.warning(f"PDF generation failed: {e}. Markdown still saved.")

        return output_paths

    def _render_markdown(self, ctx: Dict) -> str:
        a, an = ctx["alert"], ctx["analysis"]
        score = an.get("severity_score", 0)
        tier = an.get("_analysis_tier", "fast")
        model_used = an.get("_ai_model", "unknown")

        steps_md = lambda steps: "\n".join(f"{i+1}. {s}" for i, s in enumerate(steps))

        return f"""# 🛡️ Incident Triage Report

**Report ID:** {ctx["report_id"]}
**Generated:** {ctx["generated_at"]}
**AI Model:** {model_used} (analysis tier: **{tier}**)
**Severity:** {ctx["severity_icon"]} **{score}/10 — {ctx["severity_label"]}**

---

## Alert Details

| Field | Value |
|-------|-------|
| Rule ID | {a.get("rule_id", "N/A")} |
| Rule Level | {a.get("rule_level", "N/A")}/15 |
| Rule Description | {a.get("rule_description", "N/A")} |
| Agent | {a.get("agent_name", "N/A")} ({a.get("agent_ip", "N/A")}) |
| Source IP | {a.get("source_ip", "N/A")} |
| Timestamp | {a.get("timestamp", "N/A")} |

---

## AI Analysis Summary

{an.get("summary", "No summary available.")}

---

## MITRE ATT&CK Classification

| Field | Value |
|-------|-------|
| Tactic | {an.get("mitre_tactic", "N/A")} |
| Technique | {an.get("mitre_technique", "N/A")} |
| Sub-technique | {an.get("mitre_subtechnique") or "N/A"} |

---

## Severity Assessment

**Score: {score}/10 — {ctx["severity_label"]}**

{an.get("severity_justification", "No justification provided.")}

**Escalation Required:** {"✅ YES" if an.get("escalation_needed") else "❌ No"}

---

## Investigation Steps

{steps_md(an.get("investigation_steps", ["No steps available."]))}

---

## Remediation Steps

{steps_md(an.get("remediation_steps", ["No steps available."]))}

---

## False Positive Indicators

{an.get("false_positive_indicators", "No indicators specified.")}

---

## Audit Trail

| Event | Value |
|-------|-------|
| Wazuh Alert ID | {a.get("wazuh_id", "N/A")} |
| Internal Alert ID | {a.get("alert_id", "N/A")} |
| Analysis Tier | {tier} |
| AI Model Used | {model_used} |
{f"| Fast-Pass Score (pre-escalation) | {an.get('_fast_pass_score')} |" if an.get('_fast_pass_score') else ""}

---

*Generated by AI Security Alert Triage Assistant v2.0.0 — Local LLM Edition*
*This report is AI-generated. Human analyst review is required for all HIGH and CRITICAL alerts.*
"""

    def _render_pdf(self, ctx: Dict, output_path: Path) -> None:
        """
        Render a PDF from the report using pdfkit + wkhtmltopdf.

        Windows-friendly alternative to WeasyPrint. Requires:
        1. pip install pdfkit
        2. wkhtmltopdf installed from https://wkhtmltopdf.org/downloads.html
           (default install path: C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe)
        """
        import pdfkit

        a, an = ctx["alert"], ctx["analysis"]
        score = an.get("severity_score", 0)
        severity_class = (
            "critical" if score >= 9 else
            "high" if score >= 7 else
            "medium" if score >= 4 else "low"
        )

        steps_html = lambda steps: "".join(f"<li>{s}</li>" for s in steps)

        html_content = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  body {{ font-family: 'Segoe UI', Arial, sans-serif; max-width: 800px; margin: 30px auto;
         color: #222; line-height: 1.6; font-size: 13px; }}
  h1 {{ color: #1a1a2e; border-bottom: 3px solid #e63946; padding-bottom: 8px; font-size: 22px; }}
  h2 {{ color: #16213e; border-left: 4px solid #e63946; padding-left: 10px; margin-top: 22px; font-size: 16px; }}
  table {{ border-collapse: collapse; width: 100%; margin: 12px 0; }}
  th {{ background-color: #16213e; color: white; padding: 6px 10px; text-align: left; font-size: 12px; }}
  td {{ border: 1px solid #ddd; padding: 6px 10px; font-size: 12px; }}
  tr:nth-child(even) {{ background-color: #f7f7f7; }}
  ol {{ padding-left: 20px; }}
  li {{ margin-bottom: 6px; }}
  .meta {{ background: #f0f0f5; padding: 10px 14px; border-radius: 4px; margin-bottom: 16px; font-size: 12px; }}
  .severity-badge {{ display: inline-block; padding: 3px 10px; border-radius: 4px;
                     color: white; font-weight: bold; }}
  .severity-critical {{ background-color: #dc2626; }}
  .severity-high {{ background-color: #ea580c; }}
  .severity-medium {{ background-color: #ca8a04; }}
  .severity-low {{ background-color: #16a34a; }}
  .footer {{ margin-top: 24px; padding-top: 10px; border-top: 1px solid #ccc;
            font-size: 10px; color: #777; }}
</style>
</head>
<body>

<h1>🛡️ Incident Triage Report</h1>

<div class="meta">
  <strong>Report ID:</strong> {ctx["report_id"]}<br>
  <strong>Generated:</strong> {ctx["generated_at"]}<br>
  <strong>AI Model:</strong> {an.get("_ai_model", "unknown")} (tier: {an.get("_analysis_tier", "fast")})<br>
  <strong>Severity:</strong>
  <span class="severity-badge severity-{severity_class}">{score}/10 — {ctx["severity_label"]}</span>
</div>

<h2>Alert Details</h2>
<table>
  <tr><th>Field</th><th>Value</th></tr>
  <tr><td>Rule ID</td><td>{a.get("rule_id", "N/A")}</td></tr>
  <tr><td>Rule Level</td><td>{a.get("rule_level", "N/A")}/15</td></tr>
  <tr><td>Rule Description</td><td>{a.get("rule_description", "N/A")}</td></tr>
  <tr><td>Agent</td><td>{a.get("agent_name", "N/A")} ({a.get("agent_ip", "N/A")})</td></tr>
  <tr><td>Source IP</td><td>{a.get("source_ip", "N/A")}</td></tr>
  <tr><td>Timestamp</td><td>{a.get("timestamp", "N/A")}</td></tr>
</table>

<h2>AI Analysis Summary</h2>
<p>{an.get("summary", "No summary available.")}</p>

<h2>MITRE ATT&CK Classification</h2>
<table>
  <tr><th>Field</th><th>Value</th></tr>
  <tr><td>Tactic</td><td>{an.get("mitre_tactic", "N/A")}</td></tr>
  <tr><td>Technique</td><td>{an.get("mitre_technique", "N/A")}</td></tr>
  <tr><td>Sub-technique</td><td>{an.get("mitre_subtechnique") or "N/A"}</td></tr>
</table>

<h2>Severity Assessment</h2>
<p>{an.get("severity_justification", "No justification provided.")}</p>
<p><strong>Escalation Required:</strong> {"YES" if an.get("escalation_needed") else "No"}</p>

<h2>Investigation Steps</h2>
<ol>{steps_html(an.get("investigation_steps", ["No steps available."]))}</ol>

<h2>Remediation Steps</h2>
<ol>{steps_html(an.get("remediation_steps", ["No steps available."]))}</ol>

<h2>False Positive Indicators</h2>
<p>{an.get("false_positive_indicators", "No indicators specified.")}</p>

<div class="footer">
  Generated by AI Security Alert Triage Assistant v2.0.0 — Local LLM Edition.<br>
  This report is AI-generated. Human analyst review is required for all HIGH and CRITICAL alerts.
</div>

</body>
</html>"""

        # On Windows, pdfkit needs the explicit path to wkhtmltopdf.exe
        # unless it's been added to PATH during its installer.
        wkhtmltopdf_path = self._find_wkhtmltopdf()
        config = pdfkit.configuration(wkhtmltopdf=wkhtmltopdf_path) if wkhtmltopdf_path else None

        options = {
            "page-size": "A4",
            "margin-top": "15mm",
            "margin-bottom": "15mm",
            "margin-left": "15mm",
            "margin-right": "15mm",
            "encoding": "UTF-8",
            "quiet": "",
        }

        pdfkit.from_string(html_content, str(output_path), configuration=config, options=options)

    def _find_wkhtmltopdf(self):
        """Locate wkhtmltopdf.exe on Windows if it's not on PATH."""
        import shutil
        import platform

        # If it's already on PATH, let pdfkit find it automatically
        if shutil.which("wkhtmltopdf"):
            return None

        if platform.system() == "Windows":
            common_paths = [
                r"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe",
                r"C:\Program Files (x86)\wkhtmltopdf\bin\wkhtmltopdf.exe",
            ]
            for path in common_paths:
                if Path(path).exists():
                    return path
            raise FileNotFoundError(
                "wkhtmltopdf.exe not found. Install it from "
                "https://wkhtmltopdf.org/downloads.html or add it to PATH."
            )
        return None

    def _get_severity_label(self, score: int):
        for (low, high), (label, icon) in self.SEVERITY_LABELS.items():
            if low <= score <= high:
                return label, icon
        return "UNKNOWN", "⚪"

    def _generate_report_id(self, alert: Dict) -> str:
        ts = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
        agent = alert.get("agent_name", "unknown").replace("-", "_")
        return f"TRP_{ts}_{alert.get('rule_id', 'unknown')}_{agent}"
